version: "3.9"

services:
  cripto-market-front:
    container_name: crypto-front
    image: node
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: yarn dev
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
